/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post95, git sha1 a1bb0255d) */

(* top =  1  *)
(* generator = "Amaranth" *)
module dut(set_time, seconds, minutes, hours, days, clk, rst, pwm_out);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *)
  wire [31:0] \$1 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [5:0] \$101 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$102 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$105 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$107 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$108 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [5:0] \$112 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [5:0] \$114 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$115 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$118 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *)
  wire [27:0] \$12 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$120 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$121 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [5:0] \$125 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [5:0] \$127 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$128 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$131 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$133 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$134 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [4:0] \$138 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:42" *)
  wire [27:0] \$14 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [4:0] \$140 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$141 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$144 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$146 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$147 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:42" *)
  wire [11:0] \$15 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [4:0] \$151 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [4:0] \$153 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$154 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$157 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$159 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$160 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [8:0] \$164 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [8:0] \$166 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$167 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$170 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$172 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$173 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [8:0] \$177 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [8:0] \$179 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *)
  wire [28:0] \$18 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$180 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$183 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$185 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$186 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [8:0] \$190 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [8:0] \$192 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$193 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$196 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$198 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$199 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *)
  wire [17:0] \$2 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:9" *)
  wire [28:0] \$20 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:90" *)
  wire \$202 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:97" *)
  wire [7:0] \$204 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:97" *)
  wire [7:0] \$205 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:90" *)
  wire \$207 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:92" *)
  wire [7:0] \$209 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:92" *)
  wire [7:0] \$210 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:94" *)
  wire \$212 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *)
  wire [29:0] \$22 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:48" *)
  wire \$25 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:50" *)
  wire \$27 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$273 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$275 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$277 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$279 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$281 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$284 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$286 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$288 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:53" *)
  wire [32:0] \$29 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$290 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$292 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$294 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$296 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$298 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *)
  wire [9:0] \$3 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:53" *)
  wire [32:0] \$30 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$300 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$303 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$305 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$307 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$309 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$312 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$314 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$316 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$318 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:48" *)
  wire \$32 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$320 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$322 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$325 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$327 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$329 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$332 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$335 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$337 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$339 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:55" *)
  wire [14:0] \$34 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$341 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$343 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$345 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$348 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:55" *)
  wire [14:0] \$35 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$350 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$352 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$354 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$356 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$358 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$360 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$362 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$365 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$368 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:66" *)
  wire [32:0] \$37 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$371 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$374 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$377 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:66" *)
  wire [31:0] \$38 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$380 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$383 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$385 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$388 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$391 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$394 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$397 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:66" *)
  wire [31:0] \$40 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$400 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$403 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$406 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$409 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$41 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$412 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$414 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$417 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$420 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$423 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$426 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$429 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$432 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$435 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$438 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:66" *)
  wire [32:0] \$44 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$441 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$443 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$446 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$449 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$452 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$455 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$458 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:67" *)
  wire [16:0] \$46 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$461 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$464 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$467 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:67" *)
  wire [16:0] \$47 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$470 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$472 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$474 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$476 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$478 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$480 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$482 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$484 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$486 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$488 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:67" *)
  wire [16:0] \$49 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$490 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$492 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$494 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$496 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$498 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$50 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$500 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$502 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$504 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$506 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$508 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$510 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
  wire \$512 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:164" *)
  wire \$514 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:67" *)
  wire [16:0] \$53 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:67" *)
  wire [16:0] \$55 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$56 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:68" *)
  wire [11:0] \$59 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *)
  wire [26:0] \$6 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:68" *)
  wire [11:0] \$60 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:68" *)
  wire [11:0] \$62 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$63 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:68" *)
  wire [11:0] \$66 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:68" *)
  wire [11:0] \$68 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$69 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:69" *)
  wire [5:0] \$72 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:69" *)
  wire [5:0] \$74 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$75 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:71" *)
  wire [17:0] \$78 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:71" *)
  wire [16:0] \$79 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:41" *)
  wire [26:0] \$8 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:71" *)
  wire [16:0] \$81 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$82 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [5:0] \$86 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [5:0] \$88 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$89 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:41" *)
  wire [16:0] \$9 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$92 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [3:0] \$94 ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\back\\rtlil.py:572" *)
  wire \$95 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *)
  wire [5:0] \$99 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:76" *)
  wire [3:0] \$signal ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:76" *)
  wire [3:0] \$signal$111 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:76" *)
  wire [3:0] \$signal$124 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:76" *)
  wire [3:0] \$signal$137 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:76" *)
  wire [3:0] \$signal$150 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:76" *)
  wire [3:0] \$signal$163 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:76" *)
  wire [3:0] \$signal$176 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:76" *)
  wire [3:0] \$signal$189 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$214 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$215 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$216 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$217 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$218 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$219 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$220 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$221 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$222 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$223 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$224 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$225 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$226 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$227 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$228 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$229 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$230 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$231 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$232 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$233 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$234 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$235 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$236 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$237 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$238 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$239 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$240 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$241 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$242 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$243 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$244 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$245 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$246 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$247 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$248 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$249 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$250 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$251 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$252 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$253 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$254 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$255 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$256 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$257 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$258 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$259 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$260 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$261 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$262 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$263 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$264 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$265 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$266 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$267 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$268 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$269 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$270 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$271 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$272 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$283 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$302 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$311 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$324 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$331 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$334 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$347 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$364 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$367 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$370 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$373 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$376 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$379 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$382 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$387 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$390 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$393 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$396 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$399 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$402 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$405 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$408 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$411 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$416 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$419 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$422 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$425 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$428 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$431 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$434 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$437 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$440 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$445 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$448 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$451 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$454 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$457 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$460 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$463 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$466 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:100" *)
  wire \$signal$469 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:76" *)
  wire [3:0] \$signal$98 ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:63" *)
  wire [17:0] bin_tod;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:88" *)
  reg [6:0] bit_clk_counter = 7'h00;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:88" *)
  reg [6:0] \bit_clk_counter$next ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:32" *)
  reg [6:0] bit_counter = 7'h00;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:32" *)
  reg [6:0] \bit_counter$next ;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\hdl\\ir.py:508" *)
  input clk;
  wire clk;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:33" *)
  reg [13:0] clk_counter = 14'h0000;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:33" *)
  reg [13:0] \clk_counter$next ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:58" *)
  wire [8:0] current_day;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:59" *)
  wire [4:0] current_hour;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:60" *)
  wire [5:0] current_minute;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:61" *)
  wire [5:0] current_second;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:12" *)
  input [8:0] days;
  wire [8:0] days;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:11" *)
  input [4:0] hours;
  wire [4:0] hours;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:21" *)
  reg [31:0] internal_seconds = 32'd0;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:21" *)
  reg [31:0] \internal_seconds$next ;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:10" *)
  input [5:0] minutes;
  wire [5:0] minutes;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:151" *)
  reg [6:0] pulse_width;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:18" *)
  output pwm_out;
  wire pwm_out;
  (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\hdl\\ir.py:508" *)
  input rst;
  wire rst;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:9" *)
  input [5:0] seconds;
  wire [5:0] seconds;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:15" *)
  input set_time;
  wire set_time;
  (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:38" *)
  reg [31:0] total_seconds;
  assign \$9  = hours * (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:41" *) 12'he10;
  assign \$99  = current_second / (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  assign \$105  = \$101  % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  assign \$8  = + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:41" *) \$9 ;
  assign \$112  = current_minute / (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 1'h1;
  assign \$118  = \$114  % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  assign \$125  = current_minute / (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  assign \$12  = $signed(\$6 ) + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *) $signed(\$8 );
  assign \$131  = \$127  % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  assign \$138  = current_hour / (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 1'h1;
  assign \$144  = \$140  % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  assign \$151  = current_hour / (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  assign \$157  = \$153  % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  assign \$15  = minutes * (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:42" *) 6'h3c;
  assign \$164  = current_day / (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 1'h1;
  assign \$14  = + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:42" *) \$15 ;
  assign \$170  = \$166  % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  assign \$177  = current_day / (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  assign \$183  = \$179  % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  assign \$18  = $signed(\$12 ) + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *) $signed(\$14 );
  assign \$190  = current_day / (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 7'h64;
  assign \$196  = \$192  % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  assign \$202  = bit_clk_counter == (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:90" *) 7'h63;
  assign \$205  = bit_clk_counter + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:97" *) 1'h1;
  assign \$207  = bit_clk_counter == (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:90" *) 7'h63;
  assign \$20  = + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:9" *) seconds;
  assign \$210  = bit_counter + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:92" *) 1'h1;
  assign \$212  = bit_counter == (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:94" *) 7'h63;
  assign \$22  = $signed(\$18 ) + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *) $signed(\$20 );
  assign \$1  = + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *) $signed(\$22 );
  assign \$25  = clk_counter == (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:48" *) 14'h270f;
  assign \$27  = internal_seconds == (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:50" *) 25'h1e1337f;
  assign \$30  = internal_seconds + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:53" *) 1'h1;
  assign \$32  = clk_counter == (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:48" *) 14'h270f;
  assign \$35  = clk_counter + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:55" *) 1'h1;
  assign \$38  = internal_seconds / (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:66" *) 17'h15180;
  assign \$3  = days - (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *) 1'h1;
  assign \$44  = \$40  + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:66" *) 1'h1;
  assign \$47  = internal_seconds % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:67" *) 17'h15180;
  assign \$2  = + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *) $signed(\$3 );
  assign \$514  = bit_clk_counter < (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:164" *) pulse_width;
  always @(posedge clk)
    internal_seconds <= \internal_seconds$next ;
  always @(posedge clk)
    clk_counter <= \clk_counter$next ;
  always @(posedge clk)
    bit_clk_counter <= \bit_clk_counter$next ;
  always @(posedge clk)
    bit_counter <= \bit_counter$next ;
  assign \$53  = \$49  / (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:67" *) 12'he10;
  assign \$60  = internal_seconds % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:68" *) 12'he10;
  assign \$66  = \$62  / (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:68" *) 6'h3c;
  assign \$6  = $signed(\$2 ) * (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:40" *) $signed(18'h15180);
  assign \$72  = internal_seconds % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:69" *) 6'h3c;
  assign \$79  = internal_seconds % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:71" *) 17'h15180;
  assign \$78  = + (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:71" *) \$81 ;
  assign \$86  = current_second / (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 1'h1;
  assign \$92  = \$88  % (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:78" *) 4'ha;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    total_seconds = 32'd0;
    (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:36" *)
    if (set_time) begin
      total_seconds = \$1 ;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \internal_seconds$next  = internal_seconds;
    (* full_case = 32'd1 *)
    (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:36" *)
    if (set_time) begin
      \internal_seconds$next  = total_seconds;
    end else begin
      (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:48" *)
      if (\$25 ) begin
        (* full_case = 32'd1 *)
        (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:50" *)
        if (\$27 ) begin
          \internal_seconds$next  = 32'd0;
        end else begin
          \internal_seconds$next  = \$30 [31:0];
        end
      end
    end
    (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    if (rst) begin
      \internal_seconds$next  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:90" *)
    if (\$202 ) begin
      \bit_clk_counter$next  = 7'h00;
    end else begin
      \bit_clk_counter$next  = \$205 [6:0];
    end
    (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    if (rst) begin
      \bit_clk_counter$next  = 7'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \bit_counter$next  = bit_counter;
    (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:90" *)
    if (\$207 ) begin
      \bit_counter$next  = \$210 [6:0];
      (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:94" *)
      if (\$212 ) begin
        \bit_counter$next  = 7'h00;
      end
    end
    (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    if (rst) begin
      \bit_counter$next  = 7'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \clk_counter$next  = clk_counter;
    (* full_case = 32'd1 *)
    (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:36" *)
    if (set_time) begin
    end else begin
      (* full_case = 32'd1 *)
      (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:48" *)
      if (\$32 ) begin
        \clk_counter$next  = 14'h0000;
      end else begin
        \clk_counter$next  = \$35 [13:0];
      end
    end
    (* src = "D:\\pypy\\lib\\site-packages\\amaranth\\hdl\\xfrm.py:503" *)
    if (rst) begin
      \clk_counter$next  = 14'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    pulse_width = 7'h00;
    (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:152" *)
    casez (bit_counter)
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h00:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$273 ) begin
            pulse_width = 7'h50;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h01:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$275 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h02:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$277 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h03:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$279 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h04:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$281 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h05:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$284 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h06:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$286 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h07:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$288 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h08:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$290 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h09:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$292 ) begin
            pulse_width = 7'h50;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h0a:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$294 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h0b:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$296 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h0c:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$298 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h0d:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$300 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h0e:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$303 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h0f:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$305 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h10:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$307 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h11:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$309 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h12:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$312 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h13:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$314 ) begin
            pulse_width = 7'h50;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h14:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$316 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h15:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$318 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h16:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$320 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h17:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$322 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h18:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$325 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h19:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$327 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h1a:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$329 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h1b:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$332 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h1c:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$335 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h1d:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$337 ) begin
            pulse_width = 7'h50;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h1e:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$339 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h1f:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$341 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h20:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$343 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h21:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$345 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h22:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$348 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h23:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$350 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h24:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$352 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h25:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$354 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h26:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$356 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h27:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$358 ) begin
            pulse_width = 7'h50;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h28:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$360 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h29:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$362 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h2a:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$365 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h2b:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$368 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h2c:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$371 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h2d:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$374 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h2e:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$377 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h2f:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$380 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h30:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$383 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h31:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$385 ) begin
            pulse_width = 7'h50;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h32:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$388 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h33:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$391 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h34:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$394 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h35:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$397 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h36:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$400 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h37:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$403 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h38:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$406 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h39:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$409 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h3a:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$412 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h3b:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$414 ) begin
            pulse_width = 7'h50;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h3c:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$417 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h3d:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$420 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h3e:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$423 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h3f:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$426 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h40:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$429 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h41:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$432 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h42:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$435 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h43:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$438 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h44:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$441 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h45:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$443 ) begin
            pulse_width = 7'h50;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h46:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$446 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h47:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$449 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h48:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$452 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h49:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$455 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h4a:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$458 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h4b:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$461 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h4c:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$464 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h4d:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$467 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h4e:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$470 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h4f:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$472 ) begin
            pulse_width = 7'h50;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h50:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$474 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h51:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$476 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h52:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$478 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h53:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$480 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h54:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$482 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h55:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$484 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h56:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$486 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h57:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$488 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h58:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$490 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h59:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$492 ) begin
            pulse_width = 7'h50;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h5a:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$494 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h5b:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$496 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h5c:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$498 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h5d:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$500 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h5e:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$502 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h5f:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$504 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h60:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$506 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h61:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$508 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h62:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$510 ) begin
            pulse_width = 7'h32;
          end else begin
            pulse_width = 7'h14;
          end
      /* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:154" */
      7'h63:
          (* full_case = 32'd1 *)
          (* src = "C:\\Users\\oldgu\\PycharmProjects\\irigb\\encoder3.py:155" *)
          if (\$512 ) begin
            pulse_width = 7'h50;
          end else begin
            pulse_width = 7'h14;
          end
    endcase
  end
  assign \$29  = \$30 ;
  assign \$34  = \$35 ;
  assign \$37  = \$44 ;
  assign \$46  = \$55 ;
  assign \$59  = \$68 ;
  assign \$204  = \$205 ;
  assign \$209  = \$210 ;
  assign \$signal$283  = 1'h0;
  assign \$signal$302  = 1'h0;
  assign \$signal$311  = 1'h0;
  assign \$signal$324  = 1'h0;
  assign \$signal$331  = 1'h0;
  assign \$signal$334  = 1'h0;
  assign \$signal$347  = 1'h0;
  assign \$signal$364  = 1'h0;
  assign \$signal$367  = 1'h0;
  assign \$signal$370  = 1'h0;
  assign \$signal$373  = 1'h0;
  assign \$signal$376  = 1'h0;
  assign \$signal$379  = 1'h0;
  assign \$signal$382  = 1'h0;
  assign \$signal$387  = 1'h0;
  assign \$signal$390  = 1'h0;
  assign \$signal$393  = 1'h0;
  assign \$signal$396  = 1'h0;
  assign \$signal$399  = 1'h0;
  assign \$signal$402  = 1'h0;
  assign \$signal$405  = 1'h0;
  assign \$signal$408  = 1'h0;
  assign \$signal$411  = 1'h0;
  assign \$signal$416  = 1'h0;
  assign \$signal$419  = 1'h0;
  assign \$signal$422  = 1'h0;
  assign \$signal$425  = 1'h0;
  assign \$signal$428  = 1'h0;
  assign \$signal$431  = 1'h0;
  assign \$signal$434  = 1'h0;
  assign \$signal$437  = 1'h0;
  assign \$signal$440  = 1'h0;
  assign \$signal$445  = 1'h0;
  assign \$signal$448  = 1'h0;
  assign \$signal$451  = 1'h0;
  assign \$signal$454  = 1'h0;
  assign \$signal$457  = 1'h0;
  assign \$signal$460  = 1'h0;
  assign \$signal$463  = 1'h0;
  assign \$signal$466  = 1'h0;
  assign \$signal$469  = 1'h0;
  assign pwm_out = \$514 ;
  assign \$signal$272  = bin_tod[17];
  assign \$signal$271  = bin_tod[16];
  assign \$signal$270  = bin_tod[15];
  assign \$signal$269  = bin_tod[14];
  assign \$signal$268  = bin_tod[13];
  assign \$signal$267  = bin_tod[12];
  assign \$signal$266  = bin_tod[11];
  assign \$signal$265  = bin_tod[10];
  assign \$signal$264  = bin_tod[9];
  assign \$signal$263  = bin_tod[8];
  assign \$signal$262  = bin_tod[7];
  assign \$signal$261  = bin_tod[6];
  assign \$signal$260  = bin_tod[5];
  assign \$signal$259  = bin_tod[4];
  assign \$signal$258  = bin_tod[3];
  assign \$signal$257  = bin_tod[2];
  assign \$signal$256  = bin_tod[1];
  assign \$signal$255  = bin_tod[0];
  assign \$signal$254  = \$signal$189 [1];
  assign \$signal$253  = \$signal$189 [0];
  assign \$signal$252  = \$signal$176 [3];
  assign \$signal$251  = \$signal$176 [2];
  assign \$signal$250  = \$signal$176 [1];
  assign \$signal$249  = \$signal$176 [0];
  assign \$signal$248  = \$signal$163 [3];
  assign \$signal$247  = \$signal$163 [2];
  assign \$signal$246  = \$signal$163 [1];
  assign \$signal$245  = \$signal$163 [0];
  assign \$signal$244  = \$signal$150 [1];
  assign \$signal$243  = \$signal$150 [0];
  assign \$signal$242  = \$signal$137 [3];
  assign \$signal$241  = \$signal$137 [2];
  assign \$signal$240  = \$signal$137 [1];
  assign \$signal$239  = \$signal$137 [0];
  assign \$signal$238  = \$signal$124 [2];
  assign \$signal$237  = \$signal$124 [1];
  assign \$signal$236  = \$signal$124 [0];
  assign \$signal$235  = \$signal$111 [3];
  assign \$signal$234  = \$signal$111 [2];
  assign \$signal$233  = \$signal$111 [1];
  assign \$signal$232  = \$signal$111 [0];
  assign \$signal$231  = \$signal$98 [2];
  assign \$signal$230  = \$signal$98 [1];
  assign \$signal$229  = \$signal$98 [0];
  assign \$signal$228  = \$signal [3];
  assign \$signal$227  = \$signal [2];
  assign \$signal$226  = \$signal [1];
  assign \$signal$225  = \$signal [0];
  assign \$signal$224  = 1'h1;
  assign \$signal$223  = 1'h1;
  assign \$signal$222  = 1'h1;
  assign \$signal$221  = 1'h1;
  assign \$signal$220  = 1'h1;
  assign \$signal$219  = 1'h1;
  assign \$signal$218  = 1'h1;
  assign \$signal$217  = 1'h1;
  assign \$signal$216  = 1'h1;
  assign \$signal$215  = 1'h1;
  assign \$signal$214  = 1'h1;
  assign \$signal$189  = \$198 ;
  assign \$signal$176  = \$185 ;
  assign \$signal$163  = \$172 ;
  assign \$signal$150  = \$159 ;
  assign \$signal$137  = \$146 ;
  assign \$signal$124  = \$133 ;
  assign \$signal$111  = \$120 ;
  assign \$signal$98  = \$107 ;
  assign \$signal  = \$94 ;
  assign bin_tod = \$78 ;
  assign current_second = \$74 ;
  assign current_minute = \$68 [5:0];
  assign current_hour = \$55 [4:0];
  assign current_day = \$44 [8:0];
  assign \$41  = 1'h0;
  assign \$40  = \$38 ;
  assign \$50  = 1'h0;
  assign \$49  = \$47 ;
  assign \$56  = 1'h0;
  assign \$55  = \$53 ;
  assign \$63  = 1'h0;
  assign \$62  = \$60 ;
  assign \$69  = 1'h0;
  assign \$68  = \$66 ;
  assign \$75  = 1'h0;
  assign \$74  = \$72 ;
  assign \$82  = 1'h0;
  assign \$81  = \$79 ;
  assign \$89  = 1'h0;
  assign \$88  = \$86 ;
  assign \$95  = 1'h0;
  assign \$94  = \$92 ;
  assign \$102  = 1'h0;
  assign \$101  = \$99 ;
  assign \$108  = 1'h0;
  assign \$107  = \$105 ;
  assign \$115  = 1'h0;
  assign \$114  = \$112 ;
  assign \$121  = 1'h0;
  assign \$120  = \$118 ;
  assign \$128  = 1'h0;
  assign \$127  = \$125 ;
  assign \$134  = 1'h0;
  assign \$133  = \$131 ;
  assign \$141  = 1'h0;
  assign \$140  = \$138 ;
  assign \$147  = 1'h0;
  assign \$146  = \$144 ;
  assign \$154  = 1'h0;
  assign \$153  = \$151 ;
  assign \$160  = 1'h0;
  assign \$159  = \$157 ;
  assign \$167  = 1'h0;
  assign \$166  = \$164 ;
  assign \$173  = 1'h0;
  assign \$172  = \$170 ;
  assign \$180  = 1'h0;
  assign \$179  = \$177 ;
  assign \$186  = 1'h0;
  assign \$185  = \$183 ;
  assign \$193  = 1'h0;
  assign \$192  = \$190 ;
  assign \$199  = 1'h0;
  assign \$198  = \$196 ;
  assign \$273  = \$signal$214 ;
  assign \$275  = \$signal$225 ;
  assign \$277  = \$signal$226 ;
  assign \$279  = \$signal$227 ;
  assign \$281  = \$signal$228 ;
  assign \$284  = \$signal$283 ;
  assign \$286  = \$signal$229 ;
  assign \$288  = \$signal$230 ;
  assign \$290  = \$signal$231 ;
  assign \$292  = \$signal$215 ;
  assign \$294  = \$signal$232 ;
  assign \$296  = \$signal$233 ;
  assign \$298  = \$signal$234 ;
  assign \$300  = \$signal$235 ;
  assign \$303  = \$signal$302 ;
  assign \$305  = \$signal$236 ;
  assign \$307  = \$signal$237 ;
  assign \$309  = \$signal$238 ;
  assign \$312  = \$signal$311 ;
  assign \$314  = \$signal$216 ;
  assign \$316  = \$signal$239 ;
  assign \$318  = \$signal$240 ;
  assign \$320  = \$signal$241 ;
  assign \$322  = \$signal$242 ;
  assign \$325  = \$signal$324 ;
  assign \$327  = \$signal$243 ;
  assign \$329  = \$signal$244 ;
  assign \$332  = \$signal$331 ;
  assign \$335  = \$signal$334 ;
  assign \$337  = \$signal$217 ;
  assign \$339  = \$signal$245 ;
  assign \$341  = \$signal$246 ;
  assign \$343  = \$signal$247 ;
  assign \$345  = \$signal$248 ;
  assign \$348  = \$signal$347 ;
  assign \$350  = \$signal$249 ;
  assign \$352  = \$signal$250 ;
  assign \$354  = \$signal$251 ;
  assign \$356  = \$signal$252 ;
  assign \$358  = \$signal$218 ;
  assign \$360  = \$signal$253 ;
  assign \$362  = \$signal$254 ;
  assign \$365  = \$signal$364 ;
  assign \$368  = \$signal$367 ;
  assign \$371  = \$signal$370 ;
  assign \$374  = \$signal$373 ;
  assign \$377  = \$signal$376 ;
  assign \$380  = \$signal$379 ;
  assign \$383  = \$signal$382 ;
  assign \$385  = \$signal$219 ;
  assign \$388  = \$signal$387 ;
  assign \$391  = \$signal$390 ;
  assign \$394  = \$signal$393 ;
  assign \$397  = \$signal$396 ;
  assign \$400  = \$signal$399 ;
  assign \$403  = \$signal$402 ;
  assign \$406  = \$signal$405 ;
  assign \$409  = \$signal$408 ;
  assign \$412  = \$signal$411 ;
  assign \$414  = \$signal$220 ;
  assign \$417  = \$signal$416 ;
  assign \$420  = \$signal$419 ;
  assign \$423  = \$signal$422 ;
  assign \$426  = \$signal$425 ;
  assign \$429  = \$signal$428 ;
  assign \$432  = \$signal$431 ;
  assign \$435  = \$signal$434 ;
  assign \$438  = \$signal$437 ;
  assign \$441  = \$signal$440 ;
  assign \$443  = \$signal$221 ;
  assign \$446  = \$signal$445 ;
  assign \$449  = \$signal$448 ;
  assign \$452  = \$signal$451 ;
  assign \$455  = \$signal$454 ;
  assign \$458  = \$signal$457 ;
  assign \$461  = \$signal$460 ;
  assign \$464  = \$signal$463 ;
  assign \$467  = \$signal$466 ;
  assign \$470  = \$signal$469 ;
  assign \$472  = \$signal$222 ;
  assign \$474  = \$signal$255 ;
  assign \$476  = \$signal$256 ;
  assign \$478  = \$signal$257 ;
  assign \$480  = \$signal$258 ;
  assign \$482  = \$signal$259 ;
  assign \$484  = \$signal$260 ;
  assign \$486  = \$signal$261 ;
  assign \$488  = \$signal$262 ;
  assign \$490  = \$signal$263 ;
  assign \$492  = \$signal$223 ;
  assign \$494  = \$signal$264 ;
  assign \$496  = \$signal$265 ;
  assign \$498  = \$signal$266 ;
  assign \$500  = \$signal$267 ;
  assign \$502  = \$signal$268 ;
  assign \$504  = \$signal$269 ;
  assign \$506  = \$signal$270 ;
  assign \$508  = \$signal$271 ;
  assign \$510  = \$signal$272 ;
  assign \$512  = \$signal$224 ;
endmodule
